name: tf-lint

on:
  workflow_call:
    inputs:
      path:
        description: "Path to directory containing Terraform code"
        type: string
        required: true
      aws_region:
        description: "AWS region to use"
        type: string
        required: true
      terraform_version:
        description: "Terraform version"
        type: string
        required: false
        default: '0.14.4'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Terraform
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    env:
      AWS_REGION: ${{ inputs.aws_region }}
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: fmt
        run: terraform fmt -check -recursive

      - name: validate
        run: |
          set -o errexit -o pipefail
          find . -name provider.tf -exec dirname '{}' ';' | while read -r dir; do
            echo -e "\n$dir -----------------------------------"
            cd "$dir"
              terraform init -backend=false >/dev/null
              terraform validate -no-color
            cd -
          done
